<?php

session_start();
$type=$_GET["type"];
//echo $type;
//echo $_SESSION["prices"][$type];
//var_dump($_SESSION["booking_data"]);




?>

	

<?php

 $apiKey = "rzp_live_0tQIDhnmYh8b5j";

?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>



<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php  echo (int)$_SESSION["prices"][$type]*100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Tripzilaa"
    data-description="proceed to pay"
    data-image="https://traidev.com/img/web-desgin-development.png"
    data-prefill.name="<?php echo $_SESSION['firstname'].' '.$_SESSION['lastname'] ;?>"
    data-prefill.email="<?php echo $_SESSION['email'];?>"
    data-prefill.contact=""
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">

</form>
<?php echo "<h3><a href=index.php>back to home </a></h3>";?>

